/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { Mesh } from 'three';

export function LogoThree(props: any) {
  const { nodes, materials } = useGLTF('/logo.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Outline as Mesh).geometry}
        material={(nodes.Outline as Mesh).material}
        scale={[1, 1.07, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Spacedrifter as Mesh).geometry}
        material={(nodes.Spacedrifter as Mesh).material}
        scale={[1, 0.7, 1]}
      />
    </group>
  );
}

useGLTF.preload('/logo.glb');
